### ISSUE TITLE
FuzzBench is borked due to gce preemptibles stockouts

### ISSUE THREAD

**Issue by inferno-chromium** [google/fuzzbench#1101]
```
$ gcloud compute instances create r-2021-02-29-aflpp-1059262 --image-family=cos-stable --image-project=cos-cloud --zone=us-central1-a --scopes=cloud-platform --no-address --machine-type=e2-standard-2 --boot-disk-size=30GB --preemptible --project=fuzzbench
WARNING: You have selected a disk size of under [200GB]. This may result in poor I/O performance. For more information, see: https://developers.google.com/compute/docs/disks#performance.
WARNING: Some requests generated warnings:
 - Disk size: '30 GB' is larger than image size: '10 GB'. You might need to resize the root repartition manually if the operating system does not support automatic resizing. See https://cloud.google.com/compute/docs/disks/add-persistent-disk#resize_pd for details.

ERROR: (gcloud.compute.instances.create) Could not fetch resource:
 - The zone 'projects/fuzzbench/zones/us-central1-a' does not have enough resources available to fulfill the request.  '(resource type:compute)'.
 ```

filed internal bug b/181618349

**Comment by inferno-chromium** [comment]
Should hopefully be fixed with https://github.com/google/fuzzbench/pull/1102 and https://github.com/google/fuzzbench/commit/4d7dba97a40ed6d511a26910807bfdd7498b6896
will keep an eye

**Comment by inferno-chromium** [comment]
Still work in progress, monitoring https://www.fuzzbench.com/reports/experimental/2021-03-03-aflpp/index.html
@vanhauser-thc fyi. can't say things fixed, this is still something happening with preemptible vms. if some preempitbles don't stick to the 23 hr mark, we get screwed as we will keep recreating vms in a loop. we have been chatting with cloud team on what is going here.

**Comment by vanhauser-thc** [comment]
yeah it is not fixed yes.
but my tests are not urgent. in case you have others waiting to have their run for a due paper submission then do them first.

**Comment by inferno-chromium** [comment]
FuzzBench is not borked, this is a fuzzer issue. Basically measurer hangs due to ~40K files in corpus. E.g. see gs://fuzzbench-data/2021-03-04-aflpp/experiment-folders/freetype2-2017-aflplusplus_introspection2/trial-1083131/corpus/corpus-archive-0043.tar.gz
Looks like aflplusplus_introspection2 is culprit. 

```
605.49 MiB  2021-03-04T10:29:29Z  gs://fuzzbench-data/2021-03-04-aflpp/experiment-folders/freetype2-2017-aflplusplus_introspection2/trial-1083131/corpus/corpus-archive-0033.tar.gz
617.88 MiB  2021-03-04T10:44:21Z  gs://fuzzbench-data/2021-03-04-aflpp/experiment-folders/freetype2-2017-aflplusplus_introspection2/trial-1083131/corpus/corpus-archive-0034.tar.gz
635.72 MiB  2021-03-04T10:59:34Z  gs://fuzzbench-data/2021-03-04-aflpp/experiment-folders/freetype2-2017-aflplusplus_introspection2/trial-1083131/corpus/corpus-archive-0035.tar.gz
651.43 MiB  2021-03-04T11:14:38Z  gs://fuzzbench-data/2021-03-04-aflpp/experiment-folders/freetype2-2017-aflplusplus_introspection2/trial-1083131/corpus/corpus-archive-0036.tar.gz
662.67 MiB  2021-03-04T11:30:09Z  gs://fuzzbench-data/2021-03-04-aflpp/experiment-folders/freetype2-2017-aflplusplus_introspection2/trial-1083131/corpus/corpus-archive-0037.tar.gz
676.65 MiB  2021-03-04T11:44:58Z  gs://fuzzbench-data/2021-03-04-aflpp/experiment-folders/freetype2-2017-aflplusplus_introspection2/trial-1083131/corpus/corpus-archive-0038.tar.gz
689.07 MiB  2021-03-04T12:00:01Z  gs://fuzzbench-data/2021-03-04-aflpp/experiment-folders/freetype2-2017-aflplusplus_introspection2/trial-1083131/corpus/corpus-archive-0039.tar.gz
699.89 MiB  2021-03-04T12:15:42Z  gs://fuzzbench-data/2021-03-04-aflpp/experiment-folders/freetype2-2017-aflplusplus_introspection2/trial-1083131/corpus/corpus-archive-0040.tar.gz
 707.5 MiB  2021-03-04T12:30:50Z  gs://fuzzbench-data/2021-03-04-aflpp/experiment-folders/freetype2-2017-aflplusplus_introspection2/trial-1083131/corpus/corpus-archive-0041.tar.gz
715.13 MiB  2021-03-04T12:46:08Z  gs://fuzzbench-data/2021-03-04-aflpp/experiment-folders/freetype2-2017-aflplusplus_introspection2/trial-1083131/corpus/corpus-archive-0042.tar.gz
722.79 MiB  2021-03-04T13:00:39Z  gs://fuzzbench-data/2021-03-04-aflpp/experiment-folders/freetype2-2017-aflplusplus_introspection2/trial-1083131/corpus/corpus-archive-0043.tar.gz
```

also, see 

```
983.44 MiB  2021-03-04T10:16:35Z  gs://fuzzbench-data/2021-03-04-aflpp/experiment-folders/freetype2-2017-aflplusplus_introspection/trial-1082861/corpus/corpus-archive-0032.tar.gz
995.29 MiB  2021-03-04T10:32:13Z  gs://fuzzbench-data/2021-03-04-aflpp/experiment-folders/freetype2-2017-aflplusplus_introspection/trial-1082861/corpus/corpus-archive-0033.tar.gz
  1008 MiB  2021-03-04T10:47:07Z  gs://fuzzbench-data/2021-03-04-aflpp/experiment-folders/freetype2-2017-aflplusplus_introspection/trial-1082861/corpus/corpus-archive-0034.tar.gz
1016.75 MiB  2021-03-04T11:02:25Z  gs://fuzzbench-data/2021-03-04-aflpp/experiment-folders/freetype2-2017-aflplusplus_introspection/trial-1082861/corpus/corpus-archive-0035.tar.gz
     1 GiB  2021-03-04T11:16:59Z  gs://fuzzbench-data/2021-03-04-aflpp/experiment-folders/freetype2-2017-aflplusplus_introspection/trial-1082861/corpus/corpus-archive-0036.tar.gz
  1.01 GiB  2021-03-04T11:32:39Z  gs://fuzzbench-data/2021-03-04-aflpp/experiment-folders/freetype2-2017-aflplusplus_introspection/trial-1082861/corpus/corpus-archive-0037.tar.gz
  1.02 GiB  2021-03-04T11:47:17Z  gs://fuzzbench-data/2021-03-04-aflpp/experiment-folders/freetype2-2017-aflplusplus_introspection/trial-1082861/corpus/corpus-archive-0038.tar.gz
  1.02 GiB  2021-03-04T12:02:34Z  gs://fuzzbench-data/2021-03-04-aflpp/experiment-folders/freetype2-2017-aflplusplus_introspection/trial-1082861/corpus/corpus-archive-0039.tar.gz
  1.03 GiB  2021-03-04T12:17:40Z  gs://fuzzbench-data/2021-03-04-aflpp/experiment-folders/freetype2-2017-aflplusplus_introspection/trial-1082861/corpus/corpus-archive-0040.tar.gz
  1.04 GiB  2021-03-04T12:32:43Z  gs://fuzzbench-data/2021-03-04-aflpp/experiment-folders/freetype2-2017-aflplusplus_introspection/trial-1082861/corpus/corpus-archive-0041.tar.gz
```

freetype2 seems to blow up aflplusplus_introspection
@vanhauser-thc - wasted some fun days debugging this, but finally caught this.

**Comment by vanhauser-thc** [comment]
that is huge ... weird that this happens there. I will push a new commit id in a few minutes ...
